name: 'Deprecate package'

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'package name'
        type: choice
        options:
          - '@vkontakte/vkui'
          - '@vkontakte/vkui-floating-ui'
          - '@vkontakte/vkui-date-fns-tz'
        required: true
      version:
        description: 'type version: x.y.z (without "v")'
        required: true
      reason:
        description: 'reason for deprecation (only latin supported)'
        required: true

run-name: Deprecate version ${{ inputs.version }}

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Deprecate version
        run: npm deprecate "${{ github.event.inputs.package_name }}@${{ github.event.inputs.version }}" "${{ github.event.inputs.reason }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
