name: 'Pull Request / Dependabot'

on:
  pull_request_target:
    types: [opened]
    branches: [master]

concurrency:
  group: pr-dependabot-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check_need_complete_update:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Check if '@playwright/test' update needs to be completed
    outputs:
      value: ${{ steps.result.outputs.value }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Check is '@playwrgiht/test'
        id: result
        run: echo "value=${{ contains(steps.metadata.outputs.dependency-names, '@playwright/test') }}" >> "$GITHUB_OUTPUT"

  complete_update:
    needs: check_need_complete_update
    if: ${{ fromJSON(needs.check_need_complete_update.outputs.value) }}
    runs-on: ubuntu-latest
    name: Complete '@playwright/test' update
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Complete Playwright update
        if: ${{ contains(steps.metadata.outputs.dependency-names, '@playwright/test') }}
        uses: ./.github/actions/complete_playwright_update
        with:
          branch: ${{ github.ref }}
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          prev_version: ${{ steps.metadata.outputs.previous-version }}
          next_version: ${{ steps.metadata.outputs.new-version }}
